-- 1. Crear usuario y base de datos
DROP DATABASE IF EXISTS asesoftware;
DROP USER IF EXISTS asesoftware;

CREATE USER asesoftware WITH PASSWORD 'test';

CREATE DATABASE asesoftware
  WITH OWNER = asesoftware
       ENCODING = 'UTF8'
       LC_COLLATE = 'en_US.UTF-8'
       LC_CTYPE = 'en_US.UTF-8'
       TEMPLATE = template0;

-- Conectar a la base de datos creada

-- 2. Crear tablas con claves primarias y relaciones

-- Tabla comercios
DROP TABLE IF EXISTS public.comercios CASCADE;

CREATE TABLE public.comercios (
    id_comercio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_comercio VARCHAR(255),
    aforo_maximo INT
);

-- Tabla servicios
DROP TABLE IF EXISTS public.servicios CASCADE;

CREATE TABLE public.servicios (
    id_servicio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom_servicio VARCHAR(255),
    duracion INT,
    hora_apertura TIME,
    hora_cierre TIME,
    id_comercio BIGINT NOT NULL,
    CONSTRAINT fk_servicios_comercios FOREIGN KEY (id_comercio)
      REFERENCES public.comercios (id_comercio) ON DELETE CASCADE
);

-- Tabla turnos
DROP TABLE IF EXISTS public.turnos CASCADE;

CREATE TABLE public.turnos (
    id_turno BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_turno TIMESTAMP,
    hora_inicio TIME,
    hora_fin TIME,
    estado VARCHAR(255),
    id_servicio BIGINT NOT NULL,
    CONSTRAINT fk_turnos_servicios FOREIGN KEY (id_servicio)
      REFERENCES public.servicios (id_servicio) ON DELETE CASCADE
);

-- 3. Insertar datos iniciales

INSERT INTO public.comercios (aforo_maximo, nombre_comercio) VALUES
(10, 'Restaurante'),
(4, 'Lava Autos'),
(4, 'Salon de Belleza'),
(5, 'Farmacia');

INSERT INTO public.servicios (duracion, hora_apertura, hora_cierre, id_comercio, nom_servicio) VALUES
(45, '08:00:00', '09:30:00', 3, 'Corte clasico'),
(45, '08:00:00', '09:30:00', 1, 'Desayuno'),
(30, '09:30:00', '11:00:00', 1, 'Almuerzo');

-- 4. Crear procedimiento almacenado

CREATE OR REPLACE PROCEDURE public.generarturno(
    IN p_fecha_inicio timestamp without time zone,
    IN p_fecha_fin timestamp without time zone,
    IN p_id_servicio bigint
)
LANGUAGE plpgsql
AS $procedure$ 
DECLARE
    i INTEGER := 1;   
    j INTEGER := 0;   
    v_hora_apertura TIME;
    v_hora_cierre TIME;   
    v_hora_inicio TIME;
    v_hora_final TIME;
    v_duracion INTEGER;   
    v_minutos_apertura INTEGER;
    v_minutos_cierre INTEGER;
    v_minutos_totales INTEGER;
    v_cantidad_turnos INTEGER;
    dias_total INTEGER := 1;
BEGIN 
    RAISE NOTICE 'Procedimiento ejecutado';

    BEGIN
        dias_total := p_fecha_fin::date - p_fecha_inicio::date;

        SELECT s.hora_apertura, s.hora_cierre, s.duracion
        INTO v_hora_apertura, v_hora_cierre, v_duracion
        FROM public.servicios s
        WHERE s.id_servicio = p_id_servicio;           

        v_minutos_apertura := EXTRACT(HOUR FROM v_hora_apertura) * 60 + EXTRACT(MINUTE FROM v_hora_apertura);
        v_minutos_cierre := EXTRACT(HOUR FROM v_hora_cierre) * 60 + EXTRACT(MINUTE FROM v_hora_cierre);
        v_minutos_totales := v_minutos_cierre - v_minutos_apertura;

        IF v_duracion > 0 THEN
            v_cantidad_turnos := FLOOR(v_minutos_totales / v_duracion);

            FOR j IN 0..dias_total LOOP
                FOR i IN 1..v_cantidad_turnos LOOP          
                    v_hora_inicio := v_hora_apertura + ((i - 1) * v_duracion) * INTERVAL '1 minute';
                    v_hora_final := v_hora_apertura + (i * v_duracion) * INTERVAL '1 minute';	       

                    INSERT INTO public.turnos (hora_fin, hora_inicio, fecha_turno, id_servicio, estado)
                    VALUES (v_hora_final, v_hora_inicio, p_fecha_inicio + j * INTERVAL '1 day', p_id_servicio, 'A');
                END LOOP;
            END LOOP;                  
        ELSE
            RAISE NOTICE 'Duración inválida: %', v_duracion;
            RETURN;
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Se ha presentado un error al ejecutar: %', SQLERRM;
    END;
END;
$procedure$;

