spring.application.name=turnos
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5555/asesoftware
spring.datasource.username=asesoftware
spring.datasource.password=test

# Driver JDBC para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop

# (Opcional) Esquema por defecto (si lo usas explícitamente en tu base de datos)
spring.jpa.properties.hibernate.default_schema=public



