spring.application.name=turnos
server.port=9090

spring.datasource.url=jdbc:postgresql://localhost:5555/asesoftware
spring.datasource.username=asesoftware
spring.datasource.password=test

# Driver JDBC para PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Dialecto de Hibernate para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Mostrar las consultas SQL en consola
spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop

# (Opcional) Esquema por defecto (si lo usas explícitamente en tu base de datos)
spring.jpa.properties.hibernate.default_schema=public

sonar.projectKey=asesoftware-backend
sonar.projectName=asesoftware-backend
sonar.projectVersion=1.0

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_6bb2d45d35c9cd3af63df482253724de8b0a3860